---
version: 1
 
build_arg_defaults:
  EE_BASE_IMAGE: quay.io/ansible/ansible-runner:stable-2.12-latest
  #EE_BASE_IMAGE: quay.io/ansible/ansible-runner:stable-2.12-devel
 
ansible_config: ansible.cfg
 
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
 
additional_build_steps:
  prepend:
    - RUN cat /etc/os-release
  append:
    - RUN echo This is a post-install command!
    - RUN python3 -m pip install -U ansible-core==2.13.10
    - RUN ansible --version
  

