name: Build mddo-ansible-runner image

on: push

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: mddo-ansible-runner
    permissions:
      contents: read
      packages: write
    steps:
      - name: install ansible-builder
        run: |
          sudo apt install python3 python3-pip
          python3 -m pip install ansible-builder        

      - name: create ansible-builder Dockerfile
        run: |
          git clone https://github.com/ool-mddo/${{ env.IMAGE_NAME }}.git
          cd ${{ env.IMAGE_NAME }}
          cp requirements.* context/_build/
          ansible-builder create

      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./context/
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          secrets: |
            "ghp_credential=${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}"

  delete_old_container_images:
    needs: build_and_push
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete old container images
        uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ env.IMAGE_NAME }}
          package-type: 'container'
          min-versions-to-keep: 10
          delete-only-untagged-versions: 'true'            
